server:
  port: 6688
auth:
  sk: 
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEINh5IUUgMXgMdMlBkRQt4vs2qiWPsxiVOaUNrxsP/0Fn
    -----END PRIVATE KEY----
  pk: 
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEA4yBo/wUpHVws+Vjazgylw1+sEiDlV/cbBEARgiP0AHo=
    -----END PUBLIC KEY-----